# Generated by Django 3.1.5 on 2021-01-09 10:38

from django.db import migrations


def create_modules(apps, schema_editor):
    StudyingModule = apps.get_model("modules", "StudyingModule")

    module_names = ["Requirements", "Design", "Modelling", "Coding", "Testing"]
    for module_name in module_names:
        module = StudyingModule(name=module_name)
        module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_add_studyingmodule'),
    ]

    operations = [
        migrations.RunPython(create_modules),
    ]