# Generated by Django 3.1.5 on 2021-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
