# Generated by Django 3.1.5 on 2021-01-09 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Task title')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Task description')),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=50, verbose_name='Task difficulty')),
                ('type', models.CharField(blank=True, choices=[('USE_CASE', 'Use Case'), ('SEQUENCE', 'Sequence'), ('COMMUNICATION', 'Communication'), ('ACTIVITY', 'Activity'), ('CLASS', 'Class'), ('OBJECT', 'Object'), ('PACKAGE', 'Package'), ('INTERNAL_STRUCTURE', 'Internal Structure'), ('COMPONENT', 'Component'), ('DEPLOYMENT', 'Deployment')], max_length=50, null=True, verbose_name='Task type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_progress', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
