# Generated by Django 3.1.5 on 2021-01-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_fill_db'),
        ('tasks', '0001_add_task_usertaskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='modules.studyingmodule'),
        ),
    ]
