# Generated by Django 3.1.5 on 2021-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_add_etalon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskprogress',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
