# Generated by Django 3.1.5 on 2021-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_usertaskprogress_add_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskprogress',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
