# Generated by Django 3.1.5 on 2021-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_usertaskprogress_set_is_completed_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskprogress',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskprogress',
            name='nodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
